# This file is dual licensed under the terms of the Apache License, Version
# 2.0, and the BSD License. See the LICENSE file in the root of this repository
# for complete details.

from cryptography.hazmat.primitives.asymmetric import mldsa65

class MLDSA65PrivateKey: ...
class MLDSA65PublicKey: ...

def generate_key() -> mldsa65.MLDSA65PrivateKey: ...
def from_private_bytes(data: bytes) -> mldsa65.MLDSA65PrivateKey: ...
def from_public_bytes(data: bytes) -> mldsa65.MLDSA65PublicKey: ...